server:
  port: 8083

spring:
  application:
    name: Api-Gateway
  cloud:
    gateway:
      routes:
        - id: Quiz-Service
          uri: lb://Quiz-Service
          predicates:
            - Path=/quiz/**,/quiz-test/**
        - id: Question-Service
          uri: lb://Question-Service
          predicates:
            - Path=/question/**
