spring:
  application:
    name: Quiz-Service
  datasource:
    url: jdbc:mysql://localhost:3306/micro
    username: root
    password: 1234
server:
  port: 8081
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
